### ISSUE TITLE
[DRAFT] EPIC: Explore Coulomb Filters For Joint Ruptures

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#337]
We want to know if we can use Kevin's suggested Coulomb Filters to generate plausible joint ruptures. We also want to keep the momentum going while Kevin has time to work on it.

The main questions we want to answer are
- How can we apply Coulomb stress to generate joint ruptures?
- How can we validate and assess the result?

The question whether Coulomb stress is appropriate for generating joint ruptures is beyond the scope of this epic.
We don't yet need to fully answer the question if we can use these filters, and we don't need production reader filters yet. 

The goal is to get an initial idea of the feasibility and to have tools in place to explore and validate the results.

- [x] Write a framework to run the new filters
- [x] Develop candidate coulomb filters
- [x] Create new reports to understand the filters
- [x] Use RSQSim rupture catalogue to validate filters

**Comment by voj** [comment]
Bruce and I gave an SRM presentation recently on the progress.

Here's the opensha part of the code: https://github.com/GNS-Science/opensha/tree/oakley/WIP
And here is the nzshm part of the code: https://github.com/GNS-Science/nzshm-opensha/tree/feature/rsqsims

Once there's documentation on how to run this, we can close this epic
