### ISSUE TITLE
EPIC: Fault Model updates

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#86]
New crustal FM required to remove unwanted class of faults (many with 0 slip rates) + new Puysegur Subduction FM is needed.

Done When:
 - [x] #90
 - [x] add updated crustal FM in Stirling 2010 depths to project
 - [x] Produce New Coulomb Rupture set with similar config to RmlsZTozMDMuMEJCOVVY D90
 - [x] Produce New Coulomb Rupture set with similar config to RmlsZTo4NTkuMDM2Z2Rw Stirling 2010
 - [x] add updated GEODETIC models for new Coulomb Rupture sets to project
 - [x] Add Puysegur FM to project (need slip rate model)
 - [x] Produce Puysegur Rupture Sets

**Comment by voj** [comment]
@chrisbc see #89

**Comment by chrisbc** [comment]
> @chrisbc see #89

@voj Pls take a look at this and recommend  what if anything needs doing here. Is one of our fault model files incorrect? Maybe raise a ticket if we need to make changes, and more importantly does this impact inversions?
